const rooms=[
 {name:'ねこのへや（寝室）',bg:'assets/room-bedroom.svg',thumb:'assets/room-bedroom.svg',spots:[[12,66],[20,44],[30,78],[41,53],[50,38],[58,31],[66,62],[75,43],[84,74],[91,51],[38,23],[71,25],[53,77],[16,22],[88,25]]},
 {name:'リビング',bg:'assets/room-living.svg',thumb:'assets/room-living.svg',spots:[[14,69],[25,48],[35,30],[45,67],[54,43],[64,58],[76,37],[86,68],[91,43],[18,28],[40,79],[58,24],[72,77],[31,60]]},
 {name:'キッチン',bg:'assets/room-kitchen.svg',thumb:'assets/room-kitchen.svg',spots:[[11,63],[21,41],[31,72],[42,45],[52,68],[61,36],[71,57],[82,34],[91,70],[17,25],[38,24],[65,78],[78,76],[88,48]]}
];
const poses=['sit','side','stretch','curl','box','face','tail','tower','window','back'];
let state={room:0,found:0,total:4,running:false,paused:false,start:0,elapsed:0,targets:[],timer:null,sfx:true,bgm:true};
const $=s=>document.querySelector(s); const scene=$('#scene');
function mmss(ms){const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,cs=Math.floor(ms/10)%100;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(cs).padStart(2,'0')}`}
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function catSvg(type,pose){return `assets/${type}-${pose}.svg`}
function init(){buildStageButtons();buildPosePreview();bind();startGame(0)}
function bind(){ $('#pauseBtn').onclick=pause; $('#resumeBtn').onclick=resume; $('#restartBtn').onclick=()=>{hideModal();startGame(0)}; $('#resetBtn').onclick=()=>{localStorage.removeItem('ruiMaiBest');updateBest()}; $('#helpBtn').onclick=()=>showModal('あそびかた','部屋の中のあやしい場所をタップして、るいたん・まいたんを4匹見つけてね。全部見つけると次の部屋へ進むよ。'); $('#sfxToggle').onchange=e=>state.sfx=e.target.checked; $('#bgmToggle').onchange=e=>state.bgm=e.target.checked;}
function buildStageButtons(){const wrap=$('#stageButtons');wrap.className='stage-buttons'; rooms.forEach((r,i)=>{const b=document.createElement('button');b.className='stage-thumb';b.innerHTML=`<img src="${r.thumb}" alt=""><span>${i+1}. ${r.name.replace('（寝室）','')}</span>`;b.onclick=()=>startGame(i);wrap.appendChild(b)})}
function buildPosePreview(){const wrap=$('#posePreview');wrap.className='pose-grid';['rui','mai'].forEach(t=>poses.forEach(p=>{const img=new Image();img.src=catSvg(t,p);img.alt=t+' '+p;wrap.appendChild(img)}))}
function startGame(roomIndex){clearInterval(state.timer);state={...state,room:roomIndex,found:0,running:true,paused:false,start:performance.now(),elapsed:0,targets:[],timer:null};scene.style.backgroundImage=`url(${rooms[roomIndex].bg})`;$('#roomName').textContent=rooms[roomIndex].name;$('#stageText').textContent=`${roomIndex+1} / ${rooms.length}`;$('#foundText').textContent=`0 / ${state.total}`;document.querySelectorAll('.stage-thumb').forEach((b,i)=>b.classList.toggle('active',i===roomIndex));renderTargets();updateBest();tick();state.timer=setInterval(tick,80);hideModal()}
function renderTargets(){scene.querySelectorAll('.spot').forEach(e=>e.remove()); const spots=shuffle(rooms[state.room].spots).slice(0,state.total); const cats=shuffle([...poses]).slice(0,state.total).map((p,i)=>({type:i%2?'mai':'rui',pose:p})); spots.forEach((pt,i)=>{const b=document.createElement('button');b.className='spot';b.style.left=pt[0]+'%';b.style.top=pt[1]+'%';b.dataset.done='0'; const scale=innerWidth<760?'.82':'.92'; b.innerHTML=`<div class="cat" style="--scale:${scale}"><span class="speech">にゃ！</span><img src="${catSvg(cats[i].type,cats[i].pose)}" width="110" height="110"></div>`;b.onclick=()=>found(b);scene.appendChild(b)})}
function found(b){if(!state.running||state.paused||b.dataset.done==='1')return;b.dataset.done='1';state.found++;b.querySelector('.cat').classList.add('found');$('#foundText').textContent=`${state.found} / ${state.total}`;effects(b);beep(); if(state.found===state.total)setTimeout(clearRoom,700)}
function effects(b){const r=b.getBoundingClientRect(),sr=scene.getBoundingClientRect(); for(let i=0;i<7;i++){const e=document.createElement('div');e.className=i%2?'spark':'paw';e.textContent=i%2?'✨':'🐾';e.style.left=(r.left-sr.left+r.width/2+(Math.random()*70-35))+'px';e.style.top=(r.top-sr.top+r.height/2+(Math.random()*40-20))+'px';scene.appendChild(e);setTimeout(()=>e.remove(),950)}}
function beep(){if(!state.sfx)return;try{const ac=new (window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=740;g.gain.value=.035;o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.08)}catch(e){}}
function tick(){if(!state.running||state.paused)return;state.elapsed=performance.now()-state.start;$('#timerText').textContent=mmss(state.elapsed)}
function clearRoom(){if(state.room<rooms.length-1){showModal('ステージクリア！',`${rooms[state.room].name}クリア。次のお部屋へ行くよ！`); setTimeout(()=>startGame(state.room+1),1100)}else{state.running=false;clearInterval(state.timer);const best=Number(localStorage.getItem('ruiMaiBest')||0);if(!best||state.elapsed<best)localStorage.setItem('ruiMaiBest',String(Math.floor(state.elapsed)));updateBest();showModal('全ステージクリア！',`タイムは ${mmss(state.elapsed)}。るいたんもまいたんも見つかったよ！`)}}
function updateBest(){const best=Number(localStorage.getItem('ruiMaiBest')||0);$('#bestText').textContent=best?mmss(best):'--:--.--'}
function pause(){if(!state.running)return;state.paused=true;state.elapsed=performance.now()-state.start;showModal('ポーズ中','休憩しても大丈夫。つづきから遊べるよ。')}
function resume(){state.paused=false;state.start=performance.now()-state.elapsed;hideModal()}
function showModal(t,txt){$('#modalTitle').textContent=t;$('#modalText').textContent=txt;$('#modal').classList.remove('hidden')}
function hideModal(){$('#modal').classList.add('hidden')}
init();
